resolver: nightly-2016-10-02

packages:
- '.'
- location:
    git: https://github.com/ddssff/haskell-src-meta
    commit: b7c90892b9aceef874ddf5f3f9bd88b5a9b98f9f
  extra-dep: true

allow-newer: true

extra-deps:
- aeson-qq-0.8.1
- derive-2.5.26
- jmacro-0.6.14
- amazonka-1.4.3
- amazonka-core-1.4.3
- hse-cpp-0.1
- hsx2hs-0.13.5
- cron-0.4.1.2
- interpolate-0.1.0

- Agda-2.5.1.1
- EdisonAPI-1.3.1
- EdisonCore-1.3.1.1
- data-hash-0.2.0.1
- equivalence-0.3.1
- geniplate-mirror-0.7.4
- monadplus-1.4.2
- STMonadTrans-0.3.3

- QuasiText-0.1.2.6

- codo-notation-0.5.2
- here-1.2.8
- interpolatedstring-perl6-1.0.0

- language-c-quote-0.11.6.3
- exception-mtl-0.4.0.1
- exception-transformers-0.4.0.4
- symbol-0.2.4

flags: {}

extra-package-dbs: []

